global:
  scrape_interval: 30s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: services
    metrics_path: /q/metrics
    static_configs:
      - targets: ['myservice:8080']